[package]
name = "oxide"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
fern = "0.7.0"
log = "0.4.22"
ratatui = "0.29.0"
tokio = { version = "1.41.0", features = [ "full" ] }
